### ISSUE TITLE
(Impl) action/strategy condition in declaration?

### ISSUE THREAD

**Issue by enevoldsen1oo** [DATP4/gtl#37]
// Allow changing strategy during runtime?
strategy AdaptiveStrategy CONDITION(score > 100) {
    // Definitions for when score is greater than 100
}

// Allow condition in action parameter? Also Action as a type is a bit wonky as it is very simple to just have a function using the in-built functions as conditionals instead?
Action turn(gamestate().turn() == 4) {
    // Definitions for when the turn is 4
}

**Comment by askeko** [comment]
Not relevant anymore
